### ISSUE TITLE
Unable to pip install bicleaner

### ISSUE THREAD

**Issue by ayalda** [bitextor/bicleaner-ai#29]
When I run `pip3 install bicleaner-ai`, I get a dependency conflict as follows:

```
ERROR: Cannot install bicleaner-ai==1.0, bicleaner-ai==1.0.1, bicleaner-ai==2.0.0, bicleaner-ai==2.1.0, bicleaner-ai==2.1.1, bicleaner-ai==2.2.0, bicleaner-ai==2.2.1, bicleaner-ai==2.2.2, bicleaner-ai==2.3, bicleaner-ai==2.3.1 and bicleaner-ai==2.3.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    bicleaner-ai 2.3.2 depends on tensorflow<2.12 and >=2.6.5
    bicleaner-ai 2.3.1 depends on tensorflow<2.12 and >=2.6.5
    bicleaner-ai 2.3 depends on tensorflow<2.12 and >=2.6.5
    bicleaner-ai 2.2.2 depends on tensorflow<2.12 and >=2.6.5
    bicleaner-ai 2.2.1 depends on tensorflow<2.12 and >=2.6.5
    bicleaner-ai 2.2.0 depends on tensorflow<2.12 and >=2.6.5
    bicleaner-ai 2.1.1 depends on tensorflow<2.12 and >=2.6.5
    bicleaner-ai 2.1.0 depends on tensorflow<2.12 and >=2.6.5
    bicleaner-ai 2.0.0 depends on tensorflow<2.12 and >=2.6.5
    bicleaner-ai 1.0.1 depends on glove-python-binary==0.2.0
    bicleaner-ai 1.0 depends on glove-python-binary==0.2.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

I have tried installing on both Mac and Windows with the same result. 

I am running Python 3.11 and pip 23.3.1

I can successfully install `bicleaner` (not `bicleaner-ai`), which seem to be similar, with the `bicleaner-ai` using neural networks to run (which seems to me would be more performant as it could run on GPU). 

The dependency error seems to come from `bicleaner-ai-glove`, but any attempts to get it to install have been of no avail.

**Comment by ZJaume** [comment]
Hi @ayalda,

Probably this is because `bicleaner-ai-glove` didn't have python 3.11 binaries, but I don't really know why pip is not saying it explicitly. Anyway, I've built wheels for 3.11 and 3.12, could you please try again and see if it works?

**Comment by ayalda** [comment]
Hi @ZJaume, Thanks for the fast reply.

I tried again with the same result.

Should I try a different version of python?

**Comment by ZJaume** [comment]
It seems that Tensorflow<2.12 does not have Python 3.11 wheels. So, If you can work with 3.10 it should work. If you need to be 3.11, I have a new `bicleaner-ai` version coming that will upgrade TensorFlow.

**Comment by ZJaume** [comment]
`3.0.0` is out. It should fix your problem as it allows newer TF versions that are compatible with Python 3.11. Also note that there's also another dependency without 3.11 wheels (`cyhunspell`). So, please, install it previously or at the same time as bicleaner-ai, like the new installation instructions say:
```
pip install bicleaner-ai git+https://github.com/MSeal/cython_hunspell@2.0.3
```

**Comment by ayalda** [comment]
Great! Working now.
