### ISSUE TITLE
Installing on Windows

### ISSUE THREAD

**Issue by charliekocsis** [bitextor/bicleaner-ai#30]
I have been trying to determine the best way to install Bicleaner AI on Windows with GPU support.

I successfully installed it on WSL2 using the instructions from issue #29; however, I encountered issues with GPU compatibility. It appears that Nvidia T4 GPUs are not supported on WSL2, which only supports GeForce or Quadro GPUs.

Subsequently, I attempted to install Bicleaner AI directly on Windows and eventually succeeded. However, I am now facing a challenge with TensorFlow, as per the TensorFlow website, GPU support for native Windows installations has been discontinued starting from version 2.10.

I would appreciate any assistance or guidance you could provide.

Thank you in advance for your help.

**Comment by ZJaume** [comment]
If you need TF<2.10, maybe you can try to install Bicleaner AI v1.0.1

**Comment by charliekocsis** [comment]
Thank you very much for your answer. I managed to get it running on Google Colab so I won't pursue the Windows installation.
