### ISSUE TITLE
curious about speed

### ISSUE THREAD

**Issue by kirianguiller** [bitextor/bicleaner-ai#5]
Hi Jaume, thanks for this AI version of Bicleaner !

I was curious about the speed of the inference on your machine ?
It can be interesting to add this info to the main readme so we can compare and make better plans.

Thanks :)

**Comment by ZJaume** [comment]
Hi Kirian,

I've added a speed comparison to the README, but anyway, speed is reported on the info logs so you can check in your own hardware. It is advisable to try different batch sizes. For CPU cleaning it should be faster to run with `--processes 1` and GNU parallel running N bicleaner processes where N is the number of physical cores.

Cheers,
Jaume

**Comment by ZJaume** [comment]
Closing... feel free to open if you have further questions.
