### ISSUE TITLE
model training data

### ISSUE THREAD

**Issue by ttwelve12** [bitextor/bicleaner-ai#6]
hello, I want to know that the 100k training data is clean (wonderful) parallel corpus, or 50k clean parallel corpus(good sample) with another 50k unparallel data (noisy sample). because I find this place said: **This training will use 50000 good and 50000 bad examples.**
[https://github.com/bitextor/bicleaner#example-1](url)
Thank you~

**Comment by ZJaume** [comment]
Hi @ttwelve12,

If you are asking if you need to provide the noisy data to the training command, the answer is no. Bicleaner ai will generate the noisy sentences for you. Yo will only need to provide about 100k training samples, as much clean as you can.

**Comment by ttwelve12** [comment]
Thanks for your reply. @ZJaume So, the original Bicleaner should have 50K noisy sentences but Bicleaner ai (using neural network) only need a clean training corpus. Is right?

**Comment by ZJaume** [comment]
Well, the old Bicleaner also generates the noisy sentences since 0.13 version, but it has an option to provide noisy sentences instead. In case you want to generate them by yourself.

**Comment by ZJaume** [comment]
In any case, if you have doubts about training and don't know which options do you need, follow the training guides:

https://github.com/bitextor/bicleaner-ai/wiki/How-To-Train-Your-Bicleaner-AI

https://github.com/bitextor/bicleaner/wiki/How-to-train-your-Bicleaner

**Comment by ttwelve12** [comment]
OK, thanks~ @ZJaume

**Comment by ttwelve12** [comment]
Hello @ZJaume .  I have one more question that we just need monolingual wordfreq-is.gz, or should create wordfreq-en.gz and wordfreq-is.gz. I find, in training step, we only need one parameter : -f. But why this place said: **For this, you need a big monolingual corpus for each source language and target language.**
[https://github.com/bitextor/bicleaner-ai/wiki/How-To-Train-Your-Bicleaner-AI#word-frequency-file](url)
Thank you~

**Comment by ZJaume** [comment]
You only need frequency file for the target language

**Comment by ttwelve12** [comment]
@ZJaume OK, thank you~

**Comment by ttwelve12** [comment]
@ZJaume Hello, I'm sorry for disturbing you again. I refered to the next several line to compile kenlm:
`pip install . --install-option="--max_order 7"
mkdir -p build && cd build
cmake .. -DKENLM_MAX_ORDER=7 -DCMAKE_INSTALL_PREFIX:PATH=/your/prefix/path
make -j all install`
but still got an error:
_/data_local/kenlm/lm/model.cc:49 in void lm::ngram::detail::{anonymous}::CheckCounts(const std::vector<long unsigned int>&) threw FormatLoadException because `counts.size() > 6'._
I don't know why I can't change KENLM_MAX_ORDER. So, can I reduce my model order 7 to 6 Ngram, and how to do this, or there is a better solution？ Thank you~

**Comment by ttwelve12** [comment]
@ZJaume I modify 7gram to 5gram in bicleaner-hardrules, and the training is working. Thank you~

**Comment by ZJaume** [comment]
This has never happened to me, have you tried to reinstall from the beginning and double check that the build options are correct?

**Comment by ttwelve12** [comment]
@ZJaume I check the build options, it's same with README. And because my lm training corpus is large, I met memory error in training 6-gram ARPA file. So, finally I have to set 5-gram in bicleaner-hardrules, and it's working. Thank you~
